// <auto-generated />
namespace HardwareInventoryManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class settingtype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(settingtype));
        
        string IMigrationMetadata.Id
        {
            get { return "201509222146212_settingtype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
