//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareInventoryManager.HIResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HardwareInventoryManager.HIResources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Asset Manager.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Asset_DetailDelete_Category {
            get {
                return ResourceManager.GetString("Asset_DetailDelete_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string Asset_DetailDelete_Make {
            get {
                return ResourceManager.GetString("Asset_DetailDelete_Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Period.
        /// </summary>
        public static string Asset_DetailDelete_WarrantyPeriod {
            get {
                return ResourceManager.GetString("Asset_DetailDelete_WarrantyPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your change has not been saved, please try again..
        /// </summary>
        public static string Change_Error {
            get {
                return ResourceManager.GetString("Change_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your change has been saved..
        /// </summary>
        public static string Change_Success {
            get {
                return ResourceManager.GetString("Change_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error sending your request, please try again..
        /// </summary>
        public static string Contact_Error {
            get {
                return ResourceManager.GetString("Contact_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you. Your contact request has been sent..
        /// </summary>
        public static string Contact_Success {
            get {
                return ResourceManager.GetString("Contact_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin@myassetmanager.net.
        /// </summary>
        public static string DefaultAppEmailAddress {
            get {
                return ResourceManager.GetString("DefaultAppEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lookup cannot be deleted as it is being used..
        /// </summary>
        public static string Delete_Lookup_Error {
            get {
                return ResourceManager.GetString("Delete_Lookup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lookup type cannot be deleted as it is being used..
        /// </summary>
        public static string Delete_Lookup_Type_Error {
            get {
                return ResourceManager.GetString("Delete_Lookup_Type_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organisation cannot be deleted as it is being used..
        /// </summary>
        public static string Delete_Organisation_Error {
            get {
                return ResourceManager.GetString("Delete_Organisation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go to &lt;a href=&quot;{0}&quot;&gt;{0}&lt;/a&gt; to confirm your email address.
        /// </summary>
        public static string EmailBody_ConfirmUserEmail {
            get {
                return ResourceManager.GetString("EmailBody_ConfirmUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new account has been created for you, your username is {0} and your password is {1}. The password must be changed the first time you log in..
        /// </summary>
        public static string EmailBody_NewAccount {
            get {
                return ResourceManager.GetString("EmailBody_NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by clicking &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        public static string EmailBody_PasswordReset {
            get {
                return ResourceManager.GetString("EmailBody_PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email Address.
        /// </summary>
        public static string EmailSubject_ConfirmUserEmail {
            get {
                return ResourceManager.GetString("EmailSubject_ConfirmUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account Created.
        /// </summary>
        public static string EmailSubject_NewAccount {
            get {
                return ResourceManager.GetString("EmailSubject_NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        public static string EmailSubject_PasswordReset {
            get {
                return ResourceManager.GetString("EmailSubject_PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}. Model is missing. The Asset will not be imported..
        /// </summary>
        public static string ImportError_ModelMissing {
            get {
                return ResourceManager.GetString("ImportError_ModelMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}. Obsolesence Date is in an invalid format: {1}.
        /// </summary>
        public static string ImportError_ObsolescenseDate {
            get {
                return ResourceManager.GetString("ImportError_ObsolescenseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}. Price Paid is in an invalid format: {1}.
        /// </summary>
        public static string ImportError_PricePaid {
            get {
                return ResourceManager.GetString("ImportError_PricePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}. Purchase Date is in an invalid format: {1}.
        /// </summary>
        public static string ImportError_PurchaseDate {
            get {
                return ResourceManager.GetString("ImportError_PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}. Serial Number is missing. The Asset will not be imported..
        /// </summary>
        public static string ImportError_SerialNumberMissing {
            get {
                return ResourceManager.GetString("ImportError_SerialNumberMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string Login_Error {
            get {
                return ResourceManager.GetString("Login_Error", resourceCulture);
            }
        }
    }
}
